### ISSUE TITLE
Test if custom metrics work

### ISSUE THREAD

**Issue by JCZuurmond** [sodadata/soda-spark#77]
Test if [custom metrics](https://docs.soda.io/soda-sql/sql_metrics.html#custom-metrics) work

**Comment by albinkjellin** [comment]
I ran a test and got this stacktrace:

```
Traceback (most recent call last):
  File "/Users/albin/dev/py/env/2.1.0b14/lib/python3.9/site-packages/sodasql/scan/scan.py", line 727, in _run_sql_metric_failed_rows
    failed_rows_tuples, description = self.warehouse.sql_fetchall_description(sql=resolved_sql)
  File "/Users/albin/dev/py/env/2.1.0b14/lib/python3.9/site-packages/sodasql/scan/warehouse.py", line 36, in sql_fetchall_description
    return sql_fetchall_description(self.connection, sql)
  File "/Users/albin/dev/py/env/2.1.0b14/lib/python3.9/site-packages/sodasql/scan/db.py", line 56, in sql_fetchall_description
    cursor = connection.cursor()
AttributeError: 'SparkSession' object has no attribute 'cursor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/albin/dev/spark/inital-data-generator/sparktest.py", line 13, in <module>
    scan_result = scan.execute(scan_definition, df2)
  File "/Users/albin/dev/py/env/2.1.0b14/lib/python3.9/site-packages/sodaspark/scan.py", line 163, in execute
    scan.execute()
  File "/Users/albin/dev/py/env/2.1.0b14/lib/python3.9/site-packages/sodasql/scan/scan.py", line 91, in execute
    self._query_sql_metrics_and_run_tests()
  File "/Users/albin/dev/py/env/2.1.0b14/lib/python3.9/site-packages/sodasql/scan/scan.py", line 495, in _query_sql_metrics_and_run_tests
    self._query_sql_metrics_and_run_tests_base(self.scan_yml.sql_metric_ymls)
  File "/Users/albin/dev/py/env/2.1.0b14/lib/python3.9/site-packages/sodasql/scan/scan.py", line 513, in _query_sql_metrics_and_run_tests_base
    self._run_sql_metric_failed_rows(sql_metric, resolved_sql, scan_column)
  File "/Users/albin/dev/py/env/2.1.0b14/lib/python3.9/site-packages/sodasql/scan/scan.py", line 734, in _run_sql_metric_failed_rows
    logging.exception(f'Could not perform sql metric failed rows \n{resolved_sql}', e)
Message: 'Could not perform sql metric failed rows \nselect order_id as failed_orders\nfrom orders\nwhere ship_date < order_date;\n'
```

**Comment by JCZuurmond** [comment]
Could you retry this with the newest version?
