### ISSUE TITLE
Using the Soda Client and SQL Metrics does not work

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-spark#96]
I get an issue when running a scan that has sql metrics configured and passing the Soda Cloud client to the execute call. It works fine when running the scan without the client. The execution just hangs and I need to cancel it and then I see this error message:

```
^CERROR:root:Exception while sending command.                                   
Traceback (most recent call last):
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/py4j/clientserver.py", line 475, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
RuntimeError: reentrant call inside <_io.BufferedReader name=3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/py4j/clientserver.py", line 503, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/py4j/clientserver.py", line 475, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/pyspark/context.py", line 292, in signal_handler
    self.cancelAllJobs()
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/pyspark/context.py", line 1195, in cancelAllJobs
    self._jsc.sc().cancelAllJobs()
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/py4j/java_gateway.py", line 1309, in __call__
    return_value = get_return_value(
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/py4j/protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o14.sc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/py4j/clientserver.py", line 503, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
--- Logging error ---
Traceback (most recent call last):
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/sodasql/scan/scan.py", line 682, in _run_sql_metric_failed_rows
    self.sampler.save_sample_to_local_file_with_limit(resolved_sql, temp_file, failed_limit)
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/sodasql/scan/sampler.py", line 207, in save_sample_to_local_file_with_limit
    row = cursor.fetchone()
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/sodaspark/scan.py", line 150, in fetchone
    row = self._df.first()
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/pyspark/sql/dataframe.py", line 1617, in first
    return self.head()
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/pyspark/sql/dataframe.py", line 1603, in head
    rs = self.head(1)
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/pyspark/sql/dataframe.py", line 1605, in head
    return self.take(n)
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/pyspark/sql/dataframe.py", line 744, in take
    return self.limit(num).collect()
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/pyspark/sql/dataframe.py", line 693, in collect
    sock_info = self._jdf.collectToPython()
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/py4j/java_gateway.py", line 1309, in __call__
    return_value = get_return_value(
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/py4j/protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o3900.collectToPython

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/albin/dev/soda/pipeline-demo/soda-spark-test/soda-spark-tests.py", line 21, in <module>
    scan_result = scan.execute(scan_definition, df_ecommerce, soda_server_client=soda_server_client)
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/sodaspark/scan.py", line 294, in execute
    scan.execute()
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/sodasql/scan/scan.py", line 94, in execute
    self._query_sql_metrics_and_run_tests()
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/sodasql/scan/scan.py", line 497, in _query_sql_metrics_and_run_tests
    self._query_sql_metrics_and_run_tests_base(self.scan_yml.sql_metric_ymls)
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/sodasql/scan/scan.py", line 515, in _query_sql_metrics_and_run_tests_base
    self._run_sql_metric_failed_rows(sql_metric, resolved_sql, scan_column)
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/sodasql/scan/scan.py", line 736, in _run_sql_metric_failed_rows
    logger.exception(f'Could not perform sql metric failed rows \n{resolved_sql}', e)
Message: 'Could not perform sql metric failed rows \nselect order_id as failed_orders\nfrom orders\nwhere ship_date < order_date;\n'
Arguments: (Py4JError('An error occurred while calling o3900.collectToPython'),)
```

**Comment by JCZuurmond** [comment]
I think you have an old version. At least the following suggest that:

```
  File "/Users/albin/dev/py/env/2.1.0b20/lib/python3.9/site-packages/sodaspark/scan.py", line 150, in fetchone
    row = self._df.first()
```

where now [line 150 of scan.py](https://github.com/sodadata/soda-spark/blob/414713868ab0541c8600cdda545633132d0fe6a6/src/sodaspark/scan.py#L150) is: 

```
        if self._rows is not None and len(self._rows) > 0:
```

I think this issue was solved with the [latest release](https://github.com/sodadata/soda-spark/blob/main/CHANGELOG.md#023---2021-11-18).

**Comment by albinkjellin** [comment]
Yepp, that was it. However I ran an install before I tested it but when I created a new env then it worked.
